# /root/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi


# Put your fun stuff here.

# https://stackoverflow.com/questions/41046558/bashrc-how-to-check-in-what-terminal-the-shell-is-running
# Search history
if [[ ! -v INSIDE_EMACS ]]; then
    bind '"\e[A"':history-search-backward
    bind '"\e[B"':history-search-forward
fi

# preserve history
HISTFILESIZE=100000
HISTSIZE=100000

# don't include duplicates in history
# don't include lines beggining with spaces
HISTCONTROL=ignoreboth

# list size in megabytes
export BLOCKSIZE=M

# your favorite editor
export EDITOR=zile

alias mc='mc -d'
alias less='less -i'

stty -ixon
