# /root/.bashrc -*-Shell-script-*-

# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

# Put your fun stuff here...

unset PROMPT_COMMAND

# preserve history
HISTFILESIZE=100000
HISTSIZE=100000
shopt -s histappend

# don't include duplicates in history
# don't include lines beggining with spaces
HISTCONTROL=ignoreboth

# list size in megabytes
export BLOCKSIZE=M

# your favorite editor
for EDITOR in emacs-nox jed zile micro nano
do
    if [[ -x $(command -v $EDITOR) ]]; then
        export EDITOR
        break
    fi
    unset EDITOR
done

if [[ -f ~/.bash_aliases ]]; then
    . ~/.bash_aliases
fi

if [[ -x $(command -v emacs) ]]; then
    alias emacs='emacs -Q -nw -nbc --eval "(progn\
(setq visible-cursor nil)\
(menu-bar-mode -1)\
(defalias \`yes-or-no-p \`y-or-n-p)\
(setq scroll-step 1)\
(setq scroll-preserve-screen-position t)\
(setq scroll-error-top-bottom t)\
(setq-default tab-always-indent \`complete)\
(setq-default indent-tabs-mode nil)\
(setq backward-delete-char-untabify-method nil)\
(icomplete-vertical-mode)\
(load-theme \`modus-vivendi-tritanopia)\
(global-set-key (kbd \"C-x C-b\") \`ibuffer)\
(global-set-key (kbd \"C-z\") \`undo)\
(global-set-key (kbd \"<clearline>\") \`end-of-buffer)\
(define-key function-key-map \"\\e[7@\" [C-S-home])\
(define-key function-key-map \"\\e[8@\" [C-S-end])\
)" "$@"'
fi

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias mc='mc -d'
alias less='less -i'
alias zless='zless -i'

stty -ixon

# prompt
PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] '
