# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
   . ~/.bashrc
fi

# Put your fun stuff here...

# user's bin
PATH="${HOME}/bin:${PATH}"

# user's Racket
PATH="${HOME}/racket/bin:${PATH}"
MANPATH="${HOME}/racket/man:${MANPATH}"

export PATH
export MANPATH
