# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
   . ~/.bashrc
fi

# Put your fun stuff here...

# user's bin
[[ -d ${HOME}/bin ]] && PATH="${HOME}/bin:${PATH}"

# user's Racket
[[ -d ${HOME}/racket/bin ]] && PATH="${HOME}/racket/bin:${PATH}"
[[ -d ${HOME}/racket/man ]] && MANPATH="${HOME}/racket/man:${MANPATH}"

export PATH
export MANPATH
