#!/bin/bash

artha &

(sleep 0.4 && fbpanel --profile default) &
(sleep 0.6 && parcellite) &
(sleep 0.8 && volumeicon) &
(sleep 1.0 && hello) &

# Too much artifacts with amdgpu. Use picom (compton successor) as a workaround.
# (sleep 1.0 && lsmod | grep -q ^amdgpu && picom) &
# Start picom anyway
(sleep 2.0 && picom) &

(sleep 3.0 && conky -q -d) &
