# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# USE="bindist dist-kernel dracut -systemd -apparmor -kde -gnome -bluetooth -nls vaapi"
# USE="dist-kernel -systemd -apparmor -kde -gnome"
# USE="dist-kernel -systemd -apparmor -kde -gnome -bluetooth"
USE="dist-kernel -systemd -apparmor -kde -gnome -bluetooth -qt5 -qt6 -plasma"

# VIDEO_CARDS="amdgpu fbdev intel nouveau radeon radeonsi vesa dummy virgl"
VIDEO_CARDS="amdgpu fbdev intel nouveau radeon radeonsi vesa dummy virtio modesetting"

MAKEOPTS="-j6"

FEATURES="notitles"

# Binary Host
# https://wiki.gentoo.org/wiki/Gentoo_Binary_Host_Quickstart
FEATURES="${FEATURES} getbinpkg"
FEATURES="${FEATURES} binpkg-request-signature"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

L10N="en en-US"
