#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.


menuentry "================================================================================" {
        true
}

menuentry "System restart" {
	echo "System rebooting..."
	reboot
}

menuentry "Firmware setup" {
	fwsetup
}

menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}

menuentry "================================================================================" {
        true
}

menuentry "Boot from USB" {
	echo "Here we go..."
	set root=(hd0,gpt1)
	chainloader /efi/boot/bootx64.efi
	boot
}
